
create or replace table "KARUNA_ANALYTICS"."REPORTING"."PRESCRIBER_RX_SUMMARY" as
with union_data as (
        select 'Specialty' as DATA_SOURCE, "HCPs", initcap(INDICATION) as INDICATION, METRIC_TYPE, TIMEPERIOD, NULL AS YEAR, CLASS, DOSAGE_TYPE, BRAND_GENERIC, SPCL_GROUP, METRIC_VALUE AS VALUE, SUM_VALUE, TOTAL_WRITERS
        from "KARUNA_ANALYTICS"."REPORTING"."PRESCRIBER_RX_SUMMARY_SPEC"
    union all
        select 'Year' as DATA_SOURCE, "HCPs", initcap(INDICATION) as INDICATION, METRIC_TYPE, '' AS TIMEPERIOD, YEAR, CLASS, DOSAGE_TYPE, BRAND_GENERIC, SPCL_GROUP, METRIC_VALUE AS VALUE, SUM_VALUE, TOTAL_WRITERS
        from "KARUNA_ANALYTICS"."REPORTING"."PRESCRIBER_RX_SUMMARY_YEAR"
    union all
        select 'Year - Decile' as DATA_SOURCE, "HCPs", initcap(INDICATION) as INDICATION, METRIC_TYPE, '' AS TIMEPERIOD, YEAR, CLASS, DOSAGE_TYPE, BRAND_GENERIC, SPCL_GROUP, METRIC_VALUE AS VALUE, SUM_VALUE, TOTAL_WRITERS
        from "KARUNA_ANALYTICS"."REPORTING"."PRESCRIBER_RX_SUMMARY_YEAR_DECILE"
    union all
        select 'Specialty - Decile' as DATA_SOURCE, "HCPs", initcap(INDICATION) as INDICATION, METRIC_TYPE, TIMEPERIOD, NULL AS YEAR, CLASS, DOSAGE_TYPE, BRAND_GENERIC, SPCL_GROUP, METRIC_VALUE AS VALUE, SUM_VALUE, TOTAL_WRITERS
        from "KARUNA_ANALYTICS"."REPORTING"."PRESCRIBER_RX_SUMMARY_SPEC_DECILE"
)
, t0 as (
    select max(date_format) as DATA_DATE
    from (
        SELECT TO_DATE(MONTH_ID || '01', 'YYYYMMDD') AS DATE_FORMAT
        FROM "KARUNA_ANALYTICS"."ADM"."PROVIDER_RX"
    )
)
, t1 as
(
    select *
    from t0 cross join union_data
)
select * from t1;

select * from "KARUNA_ANALYTICS"."REPORTING"."PRESCRIBER_RX_SUMMARY"; where data_source = 'Year';

select distinct data_source, spcl_group from "KARUNA_ANALYTICS"."REPORTING"."PRESCRIBER_RX_SUMMARY";

