ALTER TABLE KARUNA_ANALYTICS.REPORTING.SOB_OUTPUT
RENAME COLUMN qtr TO quarter,
RENAME COLUMN Switch_from_treatment_class to Patient_category,
RENAME COLUMN Switch_to TO sob;

ALTER TABLE KARUNA_ANALYTICS.REPORTING.SOB_OUTPUT
DROP COLUMN study_month;

ALTER TABLE KARUNA_ANALYTICS.REPORTING.SOB_TABLEAU
DROP COLUMN switch_to;

ALTER TABLE KARUNA_ANALYTICS.REPORTING.SOB_OUTPUT
ADD COLUMN data_date DATE DEFAULT '2023-04-30';

CREATE OR REPLACE TABLE "KARUNA_ANALYTICS"."REPORTING"."SOB_FINAL" AS
SELECT quarter, patient_category, data_date, sob, patient_count, patient_share, switch_from FROM KARUNA_ANALYTICS.REPORTING.SOB_TABLEAU
UNION ALL
SELECT quarter, patient_category, data_date, sob, patient_count, patient_share, switch_from FROM KARUNA_ANALYTICS.REPORTING.SOB_OUTPUT;
